language: rust
rust:
  - stable
  - beta
  - nightly
env:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
cache:
  apt: true
  rust-download: true
notifications:
  email:
    on_success: never

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test
after_success:
  - travis-cargo coveralls --no-sudo
sudo: false
